### ISSUE TITLE
Compile issue, error with make

### ISSUE THREAD

**Issue by Athury** [ExeClim/Isca#245]
Hi guys, I'm a new modeler and now I'm trying to run the _held_suarez_test_case.py_  following the user guide.
However, when I enter the `python held_suarez_test_case.py`  it gives out errors as follows:

> /2023-02-19 14:16:30,375 - isca - INFO - ........................................................................................................................... Makefile is ready.
2023-02-19 14:16:30,384 - isca - INFO - mpif90 -Duse_libMPI -Duse_netCDF -Duse_LARGEFILE -DINTERNAL_FILE_NML -DOVERLOAD_C8 -DRRTM_NO_COMPILE -DSOC_NO_COMPILE -I/usr/local/include  -I/usr/local/include `nf-config --fflags  --flibs` -cpp -fcray-pointer -O2 -ffree-line-length-none -fno-range-check -fdefault-real-8 -fdefault-double-8  -c -I/home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/code/src/shared/include /home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/code/src/shared/mpp/mpp_parameter.F90
**2023-02-19 14:16:30,429 - isca - INFO - /home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/code/src/shared/mpp/mpp_parameter.F90:115:42:
2023-02-19 14:16:30,429 - isca - INFO - 115 |   integer(LONG_KIND), parameter :: DOMAIN_ID_BASE=Z'0000000100000000' ! Workaround for 64bit init problem
2023-02-19 14:16:30,429 - isca - INFO - |                                          1
2023-02-19 14:16:30,429 - isca - INFO - Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
2023-02-19 14:16:30,430 - isca - INFO - /home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/code/src/shared/mpp/mpp_parameter.F90:55:49:
2023-02-19 14:16:30,430 - isca - INFO - 55 |   public :: AGRID, GLOBAL, CYCLIC, DOMAIN_ID_BASE, CENTER, CORNER
2023-02-19 14:16:30,430 - isca - INFO - |                                                 1
2023-02-19 14:16:30,430 - isca - INFO - Error: Symbol 'domain_id_base' at (1) has no IMPLICIT type**
2023-02-19 14:16:30,434 - isca - INFO - make: *** [mpp_parameter.o] Error 1
2023-02-19 14:16:30,434 - isca - INFO - ERROR: mkmf failed for held_suarez.x
Exception in thread background thread for pid 268975:
Traceback (most recent call last):
  File "/home/yrchen/miniconda3/envs/isca_env/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/yrchen/miniconda3/envs/isca_env/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yrchen/miniconda3/envs/isca_env/lib/python3.9/site-packages/sh.py", line 1654, in wrap
    fn(*rgs, **kwargs)
  File "/home/yrchen/miniconda3/envs/isca_env/lib/python3.9/site-packages/sh.py", line 2656, in background_thread
    handle_exit_code(exit_code)
  File "/home/yrchen/miniconda3/envs/isca_env/lib/python3.9/site-packages/sh.py", line 2347, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/yrchen/miniconda3/envs/isca_env/lib/python3.9/site-packages/sh.py", line 838, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:
 RAN: /usr/bin/bash /home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/build/held_suarez/compile.sh
 
After checking the `compile.sh` I realized that it is the `make`that has problems, because when running `make` the same error also occurs:

>  115 |   integer(LONG_KIND), **parameter :: DOMAIN_ID_BASE=Z'0000000100000000' ! Workaround for 64bit init problem**
      |                                          1
Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
/home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/code/src/shared/mpp/mpp_parameter.F90:55:49:
   55 |   public :: AGRID, GLOBAL, CYCLIC, DOMAIN_ID_BASE, CENTER, CORNER
      |                                                 1
Error: Symbol 'domain_id_base' at (1) has no IMPLICIT type

It seems that there're some problems with the `parameter :: DOMAIN_ID_BASE=Z'0000000100000000 ! Workaround for 64bit init problem` command than I tried `make >build_log.txt`  and I get massages like(in the build_log.txt):

> /home/yrchen/miniconda3/envs/isca_env/bin/x86_64-conda-linux-gnu-gfortran -Duse_libMPI -Duse_netCDF -Duse_LARGEFILE -DINTERNAL_FILE_NML -DOVERLOAD_C8 -DRRTM_NO_COMPILE -DSOC_NO_COMPILE -I/usr/local/include  -I/usr/local/include `nf-config --fflags  --flibs` -cpp -fcray-pointer -O2 -ffree-line-length-none -fno-range-check -fdefault-real-8 -fdefault-double-8  -c -I/home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/code/src/shared/include	/home/yrchen/Model/work/codebase/_home_yrchen_Model_isca_Isca/code/src/shared/mpp/mpp_parameter.F90

I'm very confused about what has happened and not knowing what to do. 
Please help in the regard.

Thanks

Yuanrui

P.S. I set the original `emps-gv` file like:

> export F90=mpif90
export CC=mpicc
export GFDL_MKMF_TEMPLATE=gfort
module purge

Some information for my device
> CentOS 7.9
GNU Fortran (conda-forge gcc 11.3.0-19) 11.3.0

**Comment by Athury** [comment]
A new update. during my future study i figure out that this question mainly comes from the version of gcc. it seems that after gcc 10 such command is not supported anymore. 
And this could be solved in two ways.

1.  add ' -fallow-invalid-boz' to the flags
2.  downgrade the gcc to version that under 10

i've tried both of them, both work

However, now i reached a new error with the version of GLIBC, like:
`undefined reference to 'XXX@GLIBC_PRIVATE'`

> 2023-03-07 09:32:18,495 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/local/lib64/libgomp.so.1: undefined reference to `clock_getres@GLIBC_2.17'
2023-03-07 09:32:18,495 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libcurl.so.4: undefined reference to `__fdelt_chk@GLIBC_2.15'
2023-03-07 09:32:18,496 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libcurl.so.4: undefined reference to `__poll_chk@GLIBC_2.16'
2023-03-07 09:32:18,497 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `memcpy@GLIBC_2.14'
2023-03-07 09:32:18,497 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__clock_nanosleep@GLIBC_PRIVATE'
2023-03-07 09:32:18,498 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libresolv.so.2: undefined reference to `__resolv_context_get@GLIBC_PRIVATE'
2023-03-07 09:32:18,499 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__clock_gettime@GLIBC_PRIVATE'
2023-03-07 09:32:18,499 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libcurl.so.4: undefined reference to `clock_gettime@GLIBC_2.17'
2023-03-07 09:32:18,500 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__clock_getres@GLIBC_PRIVATE'
2023-03-07 09:32:18,501 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__h_errno@GLIBC_PRIVATE'
2023-03-07 09:32:18,501 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libresolv.so.2: undefined reference to `__resolv_context_get_preinit@GLIBC_PRIVATE'
2023-03-07 09:32:18,502 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__mktemp@GLIBC_PRIVATE'
2023-03-07 09:32:18,503 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libresolv.so.2: undefined reference to `__resolv_context_get_override@GLIBC_PRIVATE'
2023-03-07 09:32:18,503 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__libc_secure_getenv@GLIBC_PRIVATE'
2023-03-07 09:32:18,504 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__clock_getcpuclockid@GLIBC_PRIVATE'
2023-03-07 09:32:18,505 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__madvise@GLIBC_PRIVATE'
2023-03-07 09:32:18,505 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__getrlimit@GLIBC_PRIVATE'
2023-03-07 09:32:18,506 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libpthread.so.0: undefined reference to `__ctype_init@GLIBC_PRIVATE'
2023-03-07 09:32:18,507 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libresolv.so.2: undefined reference to `__resolv_context_put@GLIBC_PRIVATE'
2023-03-07 09:32:18,507 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libnspr4.so: undefined reference to `secure_getenv@GLIBC_2.17'
2023-03-07 09:32:18,508 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/librt.so.1: undefined reference to `__clock_settime@GLIBC_PRIVATE'
2023-03-07 09:32:18,508 - isca - INFO - /usr/local/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libresolv.so.2: undefined reference to `__sendmmsg@GLIBC_PRIVATE'
2023-03-07 09:32:18,509 - isca - INFO - collect2: error: ld returned 1 exit status
2023-03-07 09:32:18,515 - isca - INFO - make: *** [held_suarez.x] Error 1
2023-03-07 09:32:18,516 - isca - INFO - ERROR: mkmf failed for held_suarez.x

But when i check the GLIBC in my system it shows that:
``

> GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_PRIVATE

I’m wondering which GLIBC version should i install

**Comment by Athury** [comment]
A quick update!!!
This reason seems to come from the link to GLIBC, something has happend when trying to build refference to it. 
The way to solve this problem is to install another version of GLIBC. In my case, I choosed the glibc-2.21 and install in the `/opt/glibc-2.21`

Then, add another line in the `envfile` like: `export LD_LIBRARY_PATH=/opt/glibc-2.21`
and then this `undefined reference to XXX@GLIBC_XXX` disappeared!!! and the test case began to run smoothly

I'll close this issue if no other errors.
