### ISSUE TITLE
sh 2.0.0 breaks Isca installation

### ISSUE THREAD

**Issue by sit23** [ExeClim/Isca#247]
## Description
I've just tried to do a fresh install of Isca on maths2 (one of our newer linux servers here in Exeter), and it's installed the `sh` package at version 2.0.0. When I try and run the Held Suarez test case, I get the following error:

```
python held_suarez_test_case.py 
Traceback (most recent call last):
  File "/emmy-noether/home/sit204/Isca/src/extra/python/isca/helpers.py", line 69, in git_run_in_directory
    git_test = codedir_git.log('-1', '--format="%H"').stdout
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'stdout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/emmy-noether/home/sit204/Isca/exp/test_cases/held_suarez/held_suarez_test_case.py", line 10, in <module>
    cb = DryCodeBase.from_directory(GFDL_BASE)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/emmy-noether/home/sit204/Isca/src/extra/python/isca/codebase.py", line 35, in from_directory
    return cls(directory=directory, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/emmy-noether/home/sit204/Isca/src/extra/python/isca/codebase.py", line 398, in __init__
    super(GreyCodeBase, self).__init__(*args, **kwargs)
  File "/emmy-noether/home/sit204/Isca/src/extra/python/isca/codebase.py", line 86, in __init__
    self.git = git_run_in_directory(GFDL_BASE, self.codedir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/emmy-noether/home/sit204/Isca/src/extra/python/isca/helpers.py", line 73, in git_run_in_directory
    git_test = codedir_git.log('-1', '--format="%H"').stdout
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'stdout'
```

Upon closer inspection, it seems that `sh` 2.0.0 has changed its behaviour, such that the output of functions like `codedir_git.log('-1', '--format="%H"')` returns a `str` type, where previously it returned something of type `sh.RunningCommand`. The former does not have an `stdout` attr, but `sh.RunningCommand` does. This will need to be updated such that newer versions of sh can be accommodated.

**Comment by AndrewILWilliams** [comment]
Aha! I was just about to raise an issue because I'm also having a lot of problem with `sh` upon reinstalling Isca. Is there a simple fix for this?

Cheers, Andrew

**Comment by AndrewILWilliams** [comment]
I can get past it if I force `sh==1.9` in the `requirements.txt`, but I'm not sure if that's correct because I still can't get it to run...potentially a different issue though
