### ISSUE TITLE
Unclear Issue at End of Compiling held-suarez Case

### ISSUE THREAD

**Issue by mcthreems** [ExeClim/Isca#86]
After clearing up the previous issues with compiling the held-suarez test case, it seems to have finally reached the point where it officially compiles. However, the python code seems to hit some issue shortly after that isn't clearly explained in the terminal output. I've pasted in the output starting from just before the finish of the compilation. One part seems to suggest it's an issue with a git command, but I'm not really sure.

2019-04-01 14:10:20,025 - isca - INFO - mpiifort `nc-config --libs`  spectral_dynamics.o mpp_data.o affinity.o gradient_c2l.o atmosphere.o fms_io.o ic_from_external_file.o edt.o time_interp_external.o every_step_diagnostics.o tracer_manager.o mg_drag.o mpp_memutils.o strat_cloud.o diag_util.o mosaic_util.o time_interp.o random_numbers.o mosaic.o memuse.o polvani_2004.o memutils.o jablonowski_2006.o threadloc.o horiz_interp_bicubic.o astronomy.o gaussian_topog.o vert_diff.o diag_axis.o implicit.o diag_manager.o qe_moist_convection.o two_stream_gray_rad.o transforms.o vert_coordinate.o mpp_utilities.o spherical.o mpp_pset.o fms.o test_mpp_io.o idealized_moist_phys.o create_xgrid.o interp.o diag_output.o horiz_interp_conserve.o mpp_parameter.o axis_utils.o surface_flux.o platform.o fv_advection.o rad_utilities.o mpp_domains.o cg_drag.o diag_table.o diag_grid.o diffusivity.o time_manager.o spherical_fourier.o vert_advection.o tridiagonal.o atmos_model.o mpp_io.o sat_vapor_pres_k.o stable_bl_turb.o polvani_2007.o horiz_interp_spherical.o damping_driver.o topography.o monin_obukhov_kernel.o spectral_damping.o horiz_interp.o monin_obukhov.o gradient.o spectral_initialize_fields.o topo_drag.o fm_util.o fft.o rayleigh_bottom_drag.o qflux.o entrain.o horiz_interp_bilinear.o diag_data.o grid.o matrix_invert.o get_cal_time.o read_mosaic.o betts_miller.o hs_forcing.o my25_turb.o constants.o tracer_type.o sat_vapor_pres.o test_mpp_pset.o test_fms_io.o spec_mpp.o shallow_conv.o field_manager.o interpolator.o grid_fourier.o vert_turb_driver.o lscale_cond.o dry_convection.o gauss_and_legendre.o nsclock.o leapfrog.o global_integral.o ras.o topog_regularization.o mpp.o fft99.o press_and_geopot.o MersenneTwister.o horiz_interp_type.o test_mpp_domains.o mixed_layer.o water_borrowing.o test_mpp.o spectral_init_cond.o -o held_suarez.x  -L/u/local/intel/11.1/libs/netcdf/4.1.3-shared/lib -lnetcdff -lnetcdf -lmpi -shared-intel -traceback -nowarn
2019-04-01 14:10:22,000 - isca - WARNING - ipo: warning #11010: file format not recognized for /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so
2019-04-01 14:10:22,316 - isca - INFO - ld: skipping incompatible /u/local/compilers/gcc/4.9.3/lib/libgcc_s.so when searching for -lgcc_s
2019-04-01 14:10:26,471 - isca - INFO - make: `held_suarez.x' is up to date.
2019-04-01 14:10:26,472 - isca - INFO - Compilation complete.
2019-04-01 14:10:26,475 - isca - DEBUG - Making directory '/u/flashscratch/m/mmckinne/isca_work/experiment/held_suarez_default'
2019-04-01 14:10:26,537 - isca - WARNING - Tried to remove run directory but it doesnt exist
2019-04-01 14:10:26,570 - isca - INFO - Emptied run directory '/u/flashscratch/m/mmckinne/isca_work/experiment/held_suarez_default/run'
Traceback (most recent call last):
  File "held_suarez_test_case.py", line 107, in <module>
    exp.run(1, num_cores=NCORES, use_restart=False)
  File "/u/home/m/mmckinne/hab_proj/Isca/src/extra/python/isca/helpers.py", line 22, in _destructive
    return fn(*args, **kwargs)
  File "/u/home/m/mmckinne/hab_proj/Isca/src/extra/python/isca/helpers.py", line 38, in _useworkdir
    return fn(*args, **kwargs)
  File "/u/home/m/mmckinne/hab_proj/Isca/src/extra/python/isca/experiment.py", line 221, in run
    self.codebase.write_source_control_status(P(self.rundir, 'git_hash_used.txt'))
  File "/u/home/m/mmckinne/hab_proj/Isca/src/extra/python/isca/codebase.py", line 146, in write_source_control_status
    source_status = self.git.status("-b", "--porcelain").stdout.decode('utf8')
  File "/u/home/m/mmckinne/miniconda/envs/isca_env/lib/python3.7/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/u/home/m/mmckinne/miniconda/envs/isca_env/lib/python3.7/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/u/home/m/mmckinne/miniconda/envs/isca_env/lib/python3.7/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/u/home/m/mmckinne/miniconda/envs/isca_env/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_129: 

  RAN: /usr/bin/git --no-pager --git-dir=/u/flashscratch/m/mmckinne/isca_work/codebase/_u_home_m_mmckinne_hab_proj_Isca/code/.git --work-tree=/u/flashscratch/m/mmckinne/isca_work/codebase/_u_home_m_mmckinne_hab_proj_Isca/code status -b --porcelain

  STDOUT:

  STDERR:
error: unknown switch `b'
usage: git status [options] [--] <filepattern>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    --porcelain           show porcelain output format
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)

**Comment by mcthreems** [comment]
Surprisingly the issue was actually the first thing I tried. The commands in the python files for git used the option flag "-b" before "--porcelain", but the cluster I'm using apparently doesn't use the "-b" at all and just wants the "--porcelain" part. So I removed the "-b" from the two files using it and now things seem to be working.

**Comment by sit23** [comment]
OK - glad that the previous problems have been solved. The `-b` option gives branch information. I imagine the problem is that the version of git your machine is using is significantly different the ones we've tested. Do you know what version of git your cluster is using? (`git --version`). It would be good to know what version this problem arises for. We've tried to make this git part backwards compatible for older versions of git, but I don't think we've had problems with this option before, so it would be good to know.

**Comment by mcthreems** [comment]
The cluster is using git version 1.7.1. Thanks for the assistance, I've been able to get Isca running on our cluster so we should be good to go now with trying our own experiments.

**Comment by gkvallis** [comment]
We would like to have some sense of who is using Isca, and we are pleased that you are. So, if you don’t mind, mcthreems, please tell us something about yourself.

Regards,
Geoff

_________

Prof. Geoffrey Vallis
College of Engineering, Mathematics and Physical Sciences, 
University of Exeter
http://empslocal.ex.ac.uk/people/staff/gv219/ <http://empslocal.ex.ac.uk/people/staff/gv219/>

**Comment by mcthreems** [comment]
I'm a PhD student in Jonathan Mitchell's group at UCLA. I think Jonathan may have talked to you about the project we're planning that uses Isca.

**Comment by sit23** [comment]
Thanks for the update on the version. I'll do some testing and will update here.
